<a href="https://colab.research.google.com/github/jahnavi1thoom/DeepLearning/blob/main/Car_price_prediction(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/My Drive/CarPrice_dataset.csv'
df=pd.read_csv(path)
df.head()

Mounted at /content/drive

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [ ]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [ ]:
from pandas.core.arrays import categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

x=df.drop(columns='price')
y=df['price']

#identify categorical and numerical columns
categorical_cols=x.select_dtypes(include=['object']).columns.tolist()
numerical_cols=x.select_dtypes(include=['int64','float64']).columns.tolist()

#define preprocessing steps
preprocessor=ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),numerical_cols),
        ('car',OneHotEncoder(handle_unknown='ignore'),categorical_cols)

    ]
)

#apply preprocessing steps
x_processed=preprocessor.fit_transform(x)

#split the data
x_train,x_test,y_train,y_test=train_test_split(x_processed,y,test_size=0.2,random_state=42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#define the model
model=Sequential([
    Dense(512,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(256,activation='relu'),
    Dense(128,activation='relu'),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(1)
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 512)            │       102,912 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 277,505 (1.06 MB)

 Trainable params: 277,505 (1.06 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mean_absolute_error','mean_squared_error'])

In [ ]:
history=model.fit(x_train,y_train,epochs=50,validation_split=0.2,verbose=1)

Epoch 1/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 5s 538ms/step - loss: 12649.7920 - mean_absolute_error: 12649.7920 - mean_squared_error: 214518928.0000 - val_loss: 15081.7139 - val_mean_absolute_error: 15081.7139 - val_mean_squared_error: 317898624.0000
Epoch 2/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 12568.3418 - mean_absolute_error: 12568.3418 - mean_squared_error: 202784352.0000 - val_loss: 15077.6689 - val_mean_absolute_error: 15077.6689 - val_mean_squared_error: 317762336.0000
Epoch 3/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 13040.4766 - mean_absolute_error: 13040.4766 - mean_squared_error: 229476032.0000 - val_loss: 15065.8486 - val_mean_absolute_error: 15065.8486 - val_mean_squared_error: 317370848.0000
Epoch 4/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 12902.2139 - mean_absolute_error: 12902.2139 - mean_squared_error: 220149824.0000 - val_loss: 15033.4658 - val_mean_absolute_error: 15033.4658 - val_mean_squared_error: 316318496.0000
Epoch 5/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 12405.0908 - mean_absolute_error: 12405.0908 - mean_squared_error: 201875664.0000 - val_loss: 14952.9414 - val_mean_absolute_error: 14952.9414 - val_mean_squared_error: 313790880.0000
Epoch 6/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - loss: 13106.5020 - mean_absolute_error: 13106.5020 - mean_squared_error: 226719712.0000 - val_loss: 14763.6055 - val_mean_absolute_error: 14763.6055 - val_mean_squared_error: 307994464.0000
Epoch 7/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 12288.5176 - mean_absolute_error: 12288.5176 - mean_squared_error: 203691184.0000 - val_loss: 14354.4814 - val_mean_absolute_error: 14354.4814 - val_mean_squared_error: 296105248.0000
Epoch 8/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 11734.8926 - mean_absolute_error: 11734.8926 - mean_squared_error: 188166192.0000 - val_loss: 13518.4775 - val_mean_absolute_error: 13518.4775 - val_mean_squared_error: 273261280.0000
Epoch 9/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 11543.0322 - mean_absolute_error: 11543.0322 - mean_squared_error: 194346720.0000 - val_loss: 11886.3057 - val_mean_absolute_error: 11886.3057 - val_mean_squared_error: 232823648.0000
Epoch 10/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 8325.8828 - mean_absolute_error: 8325.8828 - mean_squared_error: 118316064.0000 - val_loss: 9184.8184 - val_mean_absolute_error: 9184.8184 - val_mean_squared_error: 174146112.0000
Epoch 11/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 6070.6719 - mean_absolute_error: 6070.6719 - mean_squared_error: 73158240.0000 - val_loss: 7147.5845 - val_mean_absolute_error: 7147.5845 - val_mean_squared_error: 107520352.0000
Epoch 12/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 5397.8613 - mean_absolute_error: 5397.8613 - mean_squared_error: 55852428.0000 - val_loss: 5859.9102 - val_mean_absolute_error: 5859.9102 - val_mean_squared_error: 64553116.0000
Epoch 13/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 4931.3506 - mean_absolute_error: 4931.3506 - mean_squared_error: 39408040.0000 - val_loss: 4473.8188 - val_mean_absolute_error: 4473.8188 - val_mean_squared_error: 43985484.0000
Epoch 14/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 3135.3604 - mean_absolute_error: 3135.3604 - mean_squared_error: 22354476.0000 - val_loss: 3775.4185 - val_mean_absolute_error: 3775.4185 - val_mean_squared_error: 43182364.0000
Epoch 15/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 2874.4829 - mean_absolute_error: 2874.4829 - mean_squared_error: 25008470.0000 - val_loss: 3575.1819 - val_mean_absolute_error: 3575.1819 - val_mean_squared_error: 32124702.0000
Epoch 16/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 2332.7493 - mean_absolute_error: 2332.7493 - mean_squared_error: 16018724.0000 - val_loss: 2631.5020 - val_mean_absolute_error: 2631.5020 - val_mean_squared_error: 14812027.0000
Epoch 17/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 2208.8916 - mean_absolute_error: 2208.8916 - mean_squared_error: 12777562.0000 - val_loss: 2619.1353 - val_mean_absolute_error: 2619.1353 - val_mean_squared_error: 14535465.0000
Epoch 18/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 2194.5342 - mean_absolute_error: 2194.5342 - mean_squared_error: 11926008.0000 - val_loss: 2996.8757 - val_mean_absolute_error: 2996.8757 - val_mean_squared_error: 19946542.0000
Epoch 19/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 2218.6292 - mean_absolute_error: 2218.6292 - mean_squared_error: 15124081.0000 - val_loss: 2864.3721 - val_mean_absolute_error: 2864.3721 - val_mean_squared_error: 20103710.0000
Epoch 20/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1938.5103 - mean_absolute_error: 1938.5103 - mean_squared_error: 12148877.0000 - val_loss: 2671.4971 - val_mean_absolute_error: 2671.4971 - val_mean_squared_error: 17945756.0000
Epoch 21/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1884.2980 - mean_absolute_error: 1884.2980 - mean_squared_error: 9730627.0000 - val_loss: 3183.7249 - val_mean_absolute_error: 3183.7249 - val_mean_squared_error: 26429088.0000
Epoch 22/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1797.8068 - mean_absolute_error: 1797.8068 - mean_squared_error: 10969566.0000 - val_loss: 3420.0745 - val_mean_absolute_error: 3420.0745 - val_mean_squared_error: 30114468.0000
Epoch 23/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 1872.0342 - mean_absolute_error: 1872.0342 - mean_squared_error: 12753675.0000 - val_loss: 2721.8801 - val_mean_absolute_error: 2721.8801 - val_mean_squared_error: 18615346.0000
Epoch 24/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1744.6167 - mean_absolute_error: 1744.6167 - mean_squared_error: 7986183.0000 - val_loss: 2595.3948 - val_mean_absolute_error: 2595.3948 - val_mean_squared_error: 16782478.0000
Epoch 25/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 1542.8447 - mean_absolute_error: 1542.8447 - mean_squared_error: 7439828.0000 - val_loss: 3097.6182 - val_mean_absolute_error: 3097.6182 - val_mean_squared_error: 22163546.0000
Epoch 26/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1981.7384 - mean_absolute_error: 1981.7384 - mean_squared_error: 13872086.0000 - val_loss: 2760.1055 - val_mean_absolute_error: 2760.1055 - val_mean_squared_error: 18571990.0000
Epoch 27/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1572.2050 - mean_absolute_error: 1572.2050 - mean_squared_error: 8731206.0000 - val_loss: 2633.4797 - val_mean_absolute_error: 2633.4797 - val_mean_squared_error: 16431808.0000
Epoch 28/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1581.0212 - mean_absolute_error: 1581.0212 - mean_squared_error: 8025868.0000 - val_loss: 2850.7351 - val_mean_absolute_error: 2850.7351 - val_mean_squared_error: 19293472.0000
Epoch 29/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1596.6542 - mean_absolute_error: 1596.6542 - mean_squared_error: 8981221.0000 - val_loss: 2798.2336 - val_mean_absolute_error: 2798.2336 - val_mean_squared_error: 18456136.0000
Epoch 30/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1398.7810 - mean_absolute_error: 1398.7810 - mean_squared_error: 7355944.5000 - val_loss: 2657.4624 - val_mean_absolute_error: 2657.4624 - val_mean_squared_error: 16404371.0000
Epoch 31/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1524.3251 - mean_absolute_error: 1524.3251 - mean_squared_error: 7759446.0000 - val_loss: 2404.6772 - val_mean_absolute_error: 2404.6772 - val_mean_squared_error: 12713840.0000
Epoch 32/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1359.3701 - mean_absolute_error: 1359.3701 - mean_squared_error: 5521189.5000 - val_loss: 2468.9485 - val_mean_absolute_error: 2468.9485 - val_mean_squared_error: 13493268.0000
Epoch 33/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 1239.2192 - mean_absolute_error: 1239.2192 - mean_squared_error: 5348028.0000 - val_loss: 2522.0186 - val_mean_absolute_error: 2522.0186 - val_mean_squared_error: 14266212.0000
Epoch 34/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1190.9917 - mean_absolute_error: 1190.9917 - mean_squared_error: 5297549.5000 - val_loss: 2582.6257 - val_mean_absolute_error: 2582.6257 - val_mean_squared_error: 15048729.0000
Epoch 35/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1253.4208 - mean_absolute_error: 1253.4208 - mean_squared_error: 5989853.0000 - val_loss: 2572.7229 - val_mean_absolute_error: 2572.7229 - val_mean_squared_error: 14701041.0000
Epoch 36/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1128.3215 - mean_absolute_error: 1128.3215 - mean_squared_error: 4860792.5000 - val_loss: 2653.4646 - val_mean_absolute_error: 2653.4646 - val_mean_squared_error: 15845315.0000
Epoch 37/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1055.6017 - mean_absolute_error: 1055.6017 - mean_squared_error: 4338632.0000 - val_loss: 2429.6770 - val_mean_absolute_error: 2429.6770 - val_mean_squared_error: 13242258.0000
Epoch 38/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1140.5441 - mean_absolute_error: 1140.5441 - mean_squared_error: 4258346.5000 - val_loss: 2372.5010 - val_mean_absolute_error: 2372.5010 - val_mean_squared_error: 12545286.0000
Epoch 39/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1104.4807 - mean_absolute_error: 1104.4807 - mean_squared_error: 4083530.5000 - val_loss: 2669.5769 - val_mean_absolute_error: 2669.5769 - val_mean_squared_error: 15725327.0000
Epoch 40/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1287.1235 - mean_absolute_error: 1287.1235 - mean_squared_error: 5790904.5000 - val_loss: 2471.4934 - val_mean_absolute_error: 2471.4934 - val_mean_squared_error: 13532400.0000
Epoch 41/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1035.2689 - mean_absolute_error: 1035.2689 - mean_squared_error: 3586120.0000 - val_loss: 2609.3242 - val_mean_absolute_error: 2609.3242 - val_mean_squared_error: 15004683.0000
Epoch 42/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 845.0481 - mean_absolute_error: 845.0481 - mean_squared_error: 2630576.5000 - val_loss: 2461.7883 - val_mean_absolute_error: 2461.7883 - val_mean_squared_error: 13300170.0000
Epoch 43/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 978.2720 - mean_absolute_error: 978.2720 - mean_squared_error: 3951917.7500 - val_loss: 2498.6929 - val_mean_absolute_error: 2498.6929 - val_mean_squared_error: 13811934.0000
Epoch 44/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 1011.8060 - mean_absolute_error: 1011.8060 - mean_squared_error: 4217179.0000 - val_loss: 2480.6997 - val_mean_absolute_error: 2480.6997 - val_mean_squared_error: 13611472.0000
Epoch 45/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 947.4337 - mean_absolute_error: 947.4337 - mean_squared_error: 3167417.0000 - val_loss: 2358.5591 - val_mean_absolute_error: 2358.5591 - val_mean_squared_error: 12550243.0000
Epoch 46/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1015.3792 - mean_absolute_error: 1015.3792 - mean_squared_error: 3179728.0000 - val_loss: 2416.0862 - val_mean_absolute_error: 2416.0862 - val_mean_squared_error: 13003988.0000
Epoch 47/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 861.8972 - mean_absolute_error: 861.8972 - mean_squared_error: 3205367.7500 - val_loss: 2447.7959 - val_mean_absolute_error: 2447.7959 - val_mean_squared_error: 13347035.0000
Epoch 48/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 929.6213 - mean_absolute_error: 929.6213 - mean_squared_error: 2853143.0000 - val_loss: 2439.3613 - val_mean_absolute_error: 2439.3613 - val_mean_squared_error: 13334072.0000
Epoch 49/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 819.1127 - mean_absolute_error: 819.1127 - mean_squared_error: 2751431.2500 - val_loss: 2483.2422 - val_mean_absolute_error: 2483.2422 - val_mean_squared_error: 13879039.0000
Epoch 50/50
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 855.7401 - mean_absolute_error: 855.7401 - mean_squared_error: 3363253.7500 - val_loss: 2304.5757 - val_mean_absolute_error: 2304.5757 - val_mean_squared_error: 11850763.0000

In [ ]:
#prediction
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
y_pred=model.predict(x_test)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print('MAE:',mae)
print('MSE:',mse)
print('R2:',r2)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
MAE: 2019.1323478467987
MSE: 10747329.559720248
R2: 0.8638613863347107

In [ ]:
#example new data
new_data=x.iloc[[0]]
new_data_precessed=preprocessor.transform(new_data)

predicted_price=model.predict(new_data_precessed)
print('Predicted Price:',predicted_price[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 403ms/step
Predicted Price: 14502.541